<!DOCTYPE html>
<html lang="zh-cn">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<title>错误提示</title>
		<link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.2/css/bootstrap.min.css">
	    <!--[if lt IE 9]>
	      <script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	      <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
	    <![endif]-->
	</head>
	<body>
	<style>
		.bs-callout {
			padding: 20px;
			margin: 20px 0;
			border: 1px solid #eee;
			border-left-width: 5px;
			border-radius: 3px;
		}
		.bs-callout-warning{
			border-left-color:#aa6708;
		}
	</style>	
	<div class="bs-callout bs-callout-warning">
	    <h4>错误标识:<?php echo $code;?></h4>
	    <p> 
	    	错误文件：<code><?php echo $file;?></code></br>
	    	错误行数：<code><?php echo $line;?></code></br> 
	    	错误信息：<code><?php echo $message ;?></code>  
	   	</p>
	</div>
	</body>
</html>